data:
  output_path: data/output/anomalies_batch.csv
  test_data_path: data/test/sensor_data_test.csv
  train_data_path: data/train/sensor_data_train.csv
logging:
  level: INFO
model:
  normal_mean: 50.00
  normal_std: 1.00
  threshold_multiplier: 3
